apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  
patchesStrategicMerge:
  - patch.yaml
  
images:
  - name: getting-started
    newName: hardkacr.azurecr.io/docker-getting-started
    newTag: latest
